### PR TITLE
Smaller edits and fixes for user feedback received thusfar

### PR DESCRIPTION
**Pull request by brittnylapierre**
We received some user feedback with some reports of bugs and requested enhancements.

Please see attached tickets.

### CODE REVIEW

**Review by RussellMcOrmond — COMMENTED** [review]
Very good idea. (Adding URL's to the README.md )

**Review by RussellMcOrmond — APPROVED** [review]
Looks good, but I didn't run on my own.  If you send me an image I can put it into the test environment to confirm.


I made a suggestion about defaults and a possible variable name change in #101 (Sorry, I should have put it here!)

**Comment by RussellMcOrmond** [comment]
An advantage of using an environment variable named `CAP_dockerimage` over `DOCKER_IMAGE` , is that you can set a default in cap.conf and thus the variable will never be empty.

I believe this will have an error about an undefined variable if that environment variable isn't set.

`$c->stash->{version}  = $ENV{'DOCKER_IMAGE'};`

**Comment by brittnylapierre** [comment]
@RussellMcOrmond I am resetting this branch then merging my seperate branch into it so that the test env can be clean for the maps change but also not indexed asap

**Pull request merged**
