### PR TITLE
`copresentation2` support

### LINKED ISSUE #36: Remove legacy ZFS file download support.
I believe it is time to declare the adoption of Swift as production, and assume we will no longer be attempting to point patrons at servers using ZFS.

### LINKED ISSUE #46: Determine current status of `pasplit` branch, and what image should be used for demo CAP site
Discussed in https://github.com/crkn-rcdr/puppet/issues/92

Current Docker image used for https://www-demo.canadiana.ca/ matches the December 4 date of the latest change made to https://github.com/crkn-rcdr/cap/tree/pasplit 

a_gouda.pp:$capimagedemo = 'docker.c7a.ca/cap:pasplit20201204'

### PR DESCRIPTION
**Pull request by SaschaAdler**
Creates image URLs out of Noids instead of `canonicalMaster` paths when available.

If Noids are available, rudimentary IIIF manifests can be generated. See https://www-demo.canadiana.ca/iiif/oocihm.00001/manifest for an example.

Removes references to ZFS file downloads.

This should allow the same CAP codebase to work with both the production `copresentation` database and the demo `copresentation2` database.

Closes #36.
Closes #46.

### CODE REVIEW

**Comment by SaschaAdler** [comment]
I've pushed `docker.c7a.ca/cap:20210318` with this code. I'll merge the PR tomorrow unless there are any problems with it.

**Review by RussellMcOrmond — APPROVED** [review]
Deployed, and seems to work as expected (token for path ID for images, no token for noid).

Also the "full size image" and "IIIF" is there on the demo, but not on the production site.  I'm curious what is being used to toggle those features.

**Comment by SaschaAdler** [comment]
@RussellMcOrmond check out `_build_item_mode` in `CAP/lib/CIHM/Access/Presentation/Document.pm`.

**Comment by RussellMcOrmond** [comment]
As well as `if ($item_mode eq "noid") {` for the IIIF feature.

Thanks.

**Pull request merged**
